cursor_shape block
shell_integration no-cursor
scrollback_lines 10000
sync_to_monitor yes
enabled_layouts grid
window_padding_width 2 2 0 0
active_border_color #00ff00
hide_window_decorations yes
confirm_os_window_close 0
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
inactive_border_color #525252
font_size 16.0

# active_tab_foreground   #000
# active_tab_background   #eee

# editor .